node {
  def app
  
  stage('Clone Repository') {
    checkout scm
  }
  
  stage('Build image') {
    app = docker.build("nodeapp", "./mealprep/")
  }
  
  stage('Push image to ECR') {
    docker.withRegistry(
      'https://431260421084.dkr.ecr.us-east-2.amazonaws.com',
      'ecr:us-east-2:gdp.aws.credentials'){
      app.push('latest')
    }
  }
  
  stage('Pull image to EC2') {
    sshagent(credentials : ['gdp_aws_ssh']) {
      sh "ssh -t -t -i mealprep/GDP.pem ubuntu@18.222.250.74"
      sh "ls"
      sh "docker -v"
    }
  }
}
