node {
  def app
  
  stage('Clone Repository') {
    checkout scm
  }
  
  stage('Build image') {
    app = docker.build("nodeapp", "./mealprep/")
  }
  
  stage('Push image') {
    steps{
      script{
        docker.withRegistry(
          'https://431260421084.dkr.ecr.us-east-2.amazonaws.com',
          'ecr:us-east-2:gdp.aws.credentials'){
          def myImage = docker.build('gdp_docker_repository')
          myImage.push('latest')
        }
      }
    }
  }
}
